export enum EnemyType {
  EPIC = "EPIC",
}

export enum FightReportStatus {
  PLAYER_WIN = "PLAYER_WIN",
  ENEMY_WIN = "ENEMY_WIN",
  FIGHT = "FIGHT",
  DRAW = "DRAW",
}

export enum CharacterEquipmentFields {
  HEAD = "HEAD",
  LEFT_HAND = "LEFT_HAND",
  NECK = "NECK",
  RIGHT_HAND = "RIGHT_HAND",
  CHEST = "CHEST",
  ARMS = "ARMS",
  FOOTS = "FOOTS",
}

export enum ItemType {
  WEAPON_MELEE = "WEAPON_MELEE",
  WEAPON_MELEE_TWO_HAND = "WEAPON_MELEE_TWO_HAND",
  WEAPON_RANGED = "WEAPON_RANGED",
  SHIELD = "SHIELD",
  CHEST_ARMOR = "CHEST_ARMOR",
  HELMET = "HELMET",
  GLOVES = "GLOVES",
  RING = "RING",
  NECKLACE = "NECKLACE",
  BOOTS = "BOOTS",
  LEG_ARMOR = "LEG_ARMOR",
  CONSUMABLE = "CONSUMABLE",
  NEUTRAL = "NEUTRAL",
}
